/*
 * baud.h
 *
 *  Created on: Apr 26, 2014
 *      Author: caseykuhns
 */

#ifndef BAUD_H_
#define BAUD_H_

// Auto Generated by BaudGenerator.py

#if F_CPU == 1000000
 #define BAUD_300 207
 #define BAUD_1200 51
 #define BAUD_2400 25
 #define BAUD_4800 12
 #define BAUD_9600 6
 #define BAUD_14400 3
 #define BAUD_19200 2
 #define BAUD_28800 1
 #define BAUD_38400 1
 #define BAUD_57600 0

#elif F_CPU == 1843200
 #define BAUD_300 383
 #define BAUD_1200 95
 #define BAUD_2400 47
 #define BAUD_4800 23
 #define BAUD_9600 11
 #define BAUD_14400 7
 #define BAUD_19200 5
 #define BAUD_28800 3
 #define BAUD_38400 2
 #define BAUD_57600 1
 #define BAUD_76800 1
 #define BAUD_115200 0

#elif F_CPU == 2000000
 #define BAUD_300 416
 #define BAUD_1200 103
 #define BAUD_2400 51
 #define BAUD_4800 25
 #define BAUD_9600 12
 #define BAUD_14400 8
 #define BAUD_19200 6
 #define BAUD_28800 3
 #define BAUD_38400 2
 #define BAUD_57600 1
 #define BAUD_76800 1
 #define BAUD_115200 0

#elif F_CPU == 3686400
 #define BAUD_300 767
 #define BAUD_1200 191
 #define BAUD_2400 95
 #define BAUD_4800 47
 #define BAUD_9600 23
 #define BAUD_14400 15
 #define BAUD_19200 11
 #define BAUD_28800 7
 #define BAUD_38400 5
 #define BAUD_57600 3
 #define BAUD_76800 2
 #define BAUD_115200 1
 #define BAUD_230400 0

#elif F_CPU == 4000000
 #define BAUD_300 832
 #define BAUD_1200 207
 #define BAUD_2400 103
 #define BAUD_4800 51
 #define BAUD_9600 25
 #define BAUD_14400 16
 #define BAUD_19200 12
 #define BAUD_28800 8
 #define BAUD_38400 6
 #define BAUD_57600 3
 #define BAUD_76800 2
 #define BAUD_115200 1
 #define BAUD_230400 0
 #define BAUD_250000 0

#elif F_CPU == 7372800
 #define BAUD_300 1535
 #define BAUD_1200 383
 #define BAUD_2400 191
 #define BAUD_4800 95
 #define BAUD_9600 47
 #define BAUD_14400 31
 #define BAUD_19200 23
 #define BAUD_28800 15
 #define BAUD_38400 11
 #define BAUD_57600 7
 #define BAUD_76800 5
 #define BAUD_115200 3
 #define BAUD_230400 1
 #define BAUD_250000 1

#elif F_CPU == 8000000
 #define BAUD_300 1666
 #define BAUD_1200 416
 #define BAUD_2400 207
 #define BAUD_4800 103
 #define BAUD_9600 51
 #define BAUD_14400 34
 #define BAUD_19200 25
 #define BAUD_28800 16
 #define BAUD_38400 12
 #define BAUD_57600 8
 #define BAUD_76800 6
 #define BAUD_115200 3
 #define BAUD_230400 1
 #define BAUD_250000 1
 #define BAUD_500000 0

#elif F_CPU == 11059200
 #define BAUD_300 2303
 #define BAUD_1200 575
 #define BAUD_2400 287
 #define BAUD_4800 143
 #define BAUD_9600 71
 #define BAUD_14400 47
 #define BAUD_19200 35
 #define BAUD_28800 23
 #define BAUD_38400 17
 #define BAUD_57600 11
 #define BAUD_76800 8
 #define BAUD_115200 5
 #define BAUD_230400 2
 #define BAUD_250000 2
 #define BAUD_500000 0

#elif F_CPU == 14745600
 #define BAUD_300 3071
 #define BAUD_1200 767
 #define BAUD_2400 383
 #define BAUD_4800 191
 #define BAUD_9600 95
 #define BAUD_14400 63
 #define BAUD_19200 47
 #define BAUD_28800 31
 #define BAUD_38400 23
 #define BAUD_57600 15
 #define BAUD_76800 11
 #define BAUD_115200 7
 #define BAUD_230400 3
 #define BAUD_250000 3
 #define BAUD_500000 1

#elif F_CPU == 16000000
 #define BAUD_300 3332
 #define BAUD_1200 832
 #define BAUD_2400 416
 #define BAUD_4800 207
 #define BAUD_9600 103
 #define BAUD_14400 68
 #define BAUD_19200 51
 #define BAUD_28800 34
 #define BAUD_38400 25
 #define BAUD_57600 16
 #define BAUD_76800 12
 #define BAUD_115200 8
 #define BAUD_230400 3
 #define BAUD_250000 3
 #define BAUD_500000 1
 #define BAUD_1000000 0

#elif F_CPU == 18432000
 #define BAUD_300 3839
 #define BAUD_1200 959
 #define BAUD_2400 479
 #define BAUD_4800 239
 #define BAUD_9600 119
 #define BAUD_14400 79
 #define BAUD_19200 59
 #define BAUD_28800 39
 #define BAUD_38400 29
 #define BAUD_57600 19
 #define BAUD_76800 14
 #define BAUD_115200 9
 #define BAUD_230400 4
 #define BAUD_250000 4
 #define BAUD_500000 1
 #define BAUD_1000000 0

#elif F_CPU == 20000000
 #define BAUD_1200 1041
 #define BAUD_2400 520
 #define BAUD_4800 259
 #define BAUD_9600 129
 #define BAUD_14400 86
 #define BAUD_19200 64
 #define BAUD_28800 42
 #define BAUD_38400 32
 #define BAUD_57600 21
 #define BAUD_76800 15
 #define BAUD_115200 10
 #define BAUD_230400 4
 #define BAUD_250000 4
 #define BAUD_500000 2
 #define BAUD_1000000 0

#endif

#endif /* BAUD_H_ */
